### ISSUE TITLE
video upload issue

### ISSUE THREAD

**Issue by julapy** [frmfm/FRAMED-2.0-Guide#1]
im having trouble uploading my video artwork.
its a 900MB file and so i leave it uploading in the background while i do some work or a couple times i have left it over night.
the issue is that when the video has finished uploading, the session in the browser has timed out and when i press the “UPDATE” button in the artwork section,
it takes me back to the home screen to login and the upload is lost.

im using safari 9.1 on OSX 10.11.4

**Comment by filip** [comment]
There is a limit on file uploads, its 500mb. Meaning you'll either need to compress it more or cut it :(

**Comment by julapy** [comment]
ah cool, ill cut it down.
it would be good to have that info added to the guide.
cheers!

**Comment by filip** [comment]
Done! Thanks @julapy
