### ISSUE TITLE
"failed to launch" artwork

### ISSUE THREAD

**Issue by julapy** [frmfm/FRAMED-2.0-Guide#2]
hi,

ive just purchased Osmosis by schnellebuntebilder.

when pressing play on the artwork in my collections,
it begin to launch it but it fails and give me the error below,
"failed to launch"

have tried rebooting.
also other yugop animations work after reboot.
but after launching, Osmosis by schnellebuntebilder, the FRAMED unit seems to stop responding all together, and i can't launch any other artworks.

any ideas on how to resolve?

**Comment by filip** [comment]
Can you tell me what FRAMED shell version are you running? //go to FRM.FM, then settings, devices and under the device name it will say "connected" and the version no.
